import { useEffect, useState, type ReactNode } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Plus } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/erp/AppShell";
import { PageHeader } from "@/components/erp/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { createEmployee, createProductionOrder, createRouting, createWorkcenter, getEmployees, getProductionOrders, getProducts, getRoutings, getWorkcenters, type EmployeeData, type ProductionOrderData, type ProductData, type RoutingData, type WorkcenterData } from "@/lib/api";

export const Route = createFileRoute("/manufacturing")({ component: () => <AppShell><ManufacturingPage /></AppShell> });

function ManufacturingPage() {
  const [workcenters,setWorkcenters]=useState<WorkcenterData[]>([]);
  const [routings,setRoutings]=useState<RoutingData[]>([]);
  const [employees,setEmployees]=useState<EmployeeData[]>([]);
  const [orders,setOrders]=useState<ProductionOrderData[]>([]);
  const [products,setProducts]=useState<ProductData[]>([]);
  const [wc,setWc]=useState({code:"",name:"",department:"",capacity_per_hour:"",location:""});
  const [emp,setEmp]=useState({emp_code:"",name:"",department:"",designation:""});
  const [routing,setRouting]=useState({product_id:"",version:"1",name:"",workcenter_id:"",operation:"",skill:""});
  const [order,setOrder]=useState({product_id:"",quantity:"",order_date:new Date().toISOString().slice(0,10),due_date:""});
  const load=async()=>Promise.all([getWorkcenters(),getRoutings(),getEmployees(),getProductionOrders(),getProducts()]).then(([a,b,c,d,e])=>{setWorkcenters(a);setRoutings(b);setEmployees(c);setOrders(d);setProducts(e);});
  useEffect(()=>{load().catch(e=>toast.error(e instanceof Error?e.message:"Failed to load manufacturing data"));},[]);
  const saveWc=async()=>{try{await createWorkcenter({...wc,capacity_per_hour:Number(wc.capacity_per_hour||0),status:"Available",active:true,materials:[]});toast.success("Workcenter created");setWc({code:"",name:"",department:"",capacity_per_hour:"",location:""});await load();}catch(e){toast.error(e instanceof Error?e.message:"Could not create workcenter");}};
  const saveEmp=async()=>{try{await createEmployee({...emp,active:true});toast.success("Employee created");setEmp({emp_code:"",name:"",department:"",designation:""});await load();}catch(e){toast.error(e instanceof Error?e.message:"Could not create employee");}};
  const saveRouting=async()=>{try{if(!routing.product_id||!routing.workcenter_id||!routing.operation)throw new Error("Product, workcenter and operation are required");await createRouting({product_id:routing.product_id,version:Number(routing.version||1),name:routing.name,active:true,operations:[{sequence:10,code:"OP-10",name:routing.operation,workcenter_id:routing.workcenter_id,required_skill:routing.skill,setup_minutes:0,run_minutes_per_unit:0,active:true}]});toast.success("Routing created");setRouting({product_id:"",version:"1",name:"",workcenter_id:"",operation:"",skill:""});await load();}catch(e){toast.error(e instanceof Error?e.message:"Could not create routing");}};
  const saveOrder=async()=>{try{await createProductionOrder({product_id:order.product_id,quantity:Number(order.quantity),order_date:order.order_date,due_date:order.due_date||null});toast.success("Production order created and routing assignments generated");setOrder({product_id:"",quantity:"",order_date:new Date().toISOString().slice(0,10),due_date:""});await load();}catch(e){toast.error(e instanceof Error?e.message:"Could not create production order");}};
  return <>
    <PageHeader title="Manufacturing Control" subtitle="Workcenters, routings, skills, production orders and automatic operator assignment." />
    <Tabs defaultValue="workcenters">
      <TabsList className="mb-4 flex-wrap"><TabsTrigger value="workcenters">Workcenters</TabsTrigger><TabsTrigger value="routings">Routings</TabsTrigger><TabsTrigger value="orders">Production Orders</TabsTrigger><TabsTrigger value="employees">Employees</TabsTrigger></TabsList>
      <TabsContent value="workcenters"><Form title="New workcenter" onSave={saveWc}><Field label="Code"><Input value={wc.code} onChange={e=>setWc({...wc,code:e.target.value})}/></Field><Field label="Name"><Input value={wc.name} onChange={e=>setWc({...wc,name:e.target.value})}/></Field><Field label="Department"><Input value={wc.department} onChange={e=>setWc({...wc,department:e.target.value})}/></Field><Field label="Capacity/hr"><Input type="number" value={wc.capacity_per_hour} onChange={e=>setWc({...wc,capacity_per_hour:e.target.value})}/></Field><Field label="Location"><Input value={wc.location} onChange={e=>setWc({...wc,location:e.target.value})}/></Field></Form><Table rows={workcenters.map(x=>[x.code,x.name,x.department,String(x.capacity_per_hour),x.status])}/></TabsContent>
      <TabsContent value="routings"><Form title="New routing" onSave={saveRouting}><Field label="Product"><select className="w-full rounded-md border bg-background p-2" value={routing.product_id} onChange={e=>setRouting({...routing,product_id:e.target.value})}><option value="">Select</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></Field><Field label="Version"><Input type="number" value={routing.version} onChange={e=>setRouting({...routing,version:e.target.value})}/></Field><Field label="Routing name"><Input value={routing.name} onChange={e=>setRouting({...routing,name:e.target.value})}/></Field><Field label="Workcenter"><select className="w-full rounded-md border bg-background p-2" value={routing.workcenter_id} onChange={e=>setRouting({...routing,workcenter_id:e.target.value})}><option value="">Select</option>{workcenters.map(w=><option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</select></Field><Field label="Operation"><Input value={routing.operation} onChange={e=>setRouting({...routing,operation:e.target.value})}/></Field><Field label="Required skill"><Input value={routing.skill} onChange={e=>setRouting({...routing,skill:e.target.value})}/></Field></Form><Table rows={routings.map(r=>[r.product_id,"v"+r.version,r.name,r.operations.map(o=>o.name).join(", ")])}/></TabsContent>
      <TabsContent value="orders"><Form title="New production order" onSave={saveOrder}><Field label="Product"><select className="w-full rounded-md border bg-background p-2" value={order.product_id} onChange={e=>setOrder({...order,product_id:e.target.value})}><option value="">Select</option>{products.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></Field><Field label="Quantity"><Input type="number" value={order.quantity} onChange={e=>setOrder({...order,quantity:e.target.value})}/></Field><Field label="Order date"><Input type="date" value={order.order_date} onChange={e=>setOrder({...order,order_date:e.target.value})}/></Field><Field label="Due date"><Input type="date" value={order.due_date} onChange={e=>setOrder({...order,due_date:e.target.value})}/></Field></Form><Table rows={orders.map(o=>[o.order_no,String(o.quantity),o.status,String(o.operations.length),o.operations.map(x=>x.assigned_employee_id?"Assigned":"Pending").join(", ")])}/></TabsContent>
      <TabsContent value="employees"><Form title="New employee" onSave={saveEmp}><Field label="Employee code"><Input value={emp.emp_code} onChange={e=>setEmp({...emp,emp_code:e.target.value})}/></Field><Field label="Name"><Input value={emp.name} onChange={e=>setEmp({...emp,name:e.target.value})}/></Field><Field label="Department"><Input value={emp.department} onChange={e=>setEmp({...emp,department:e.target.value})}/></Field><Field label="Designation"><Input value={emp.designation} onChange={e=>setEmp({...emp,designation:e.target.value})}/></Field></Form><Table rows={employees.map(e=>[e.emp_code,e.name,e.department,e.designation,e.active?"Active":"Inactive"])}/></TabsContent>
    </Tabs>
  </>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <div><Label className="mb-1.5 block text-xs">{label}</Label>{children}</div>}
function Form({title,onSave,children}:{title:string;onSave:()=>void;children:ReactNode}){return <div className="mb-5 rounded-lg border p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold">{title}</h3><Button onClick={onSave}><Plus className="mr-1 h-4 w-4"/>Save</Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{children}</div></div>}
function Table({rows}:{rows:string[][]}){return <div className="overflow-auto rounded-lg border"><table className="w-full text-sm"><tbody>{rows.map((r,i)=><tr key={i} className="border-b last:border-0">{r.map((x,j)=><td key={j} className="px-3 py-2">{x}</td>)}</tr>)}</tbody></table></div>}
