"""prevent duplicate dispatch for delivery

Revision ID: 137bed0425f2
Revises: 8c6f2f87a123
Create Date: 2026-08-18 10:16:56.112916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137bed0425f2'
down_revision: Union[str, Sequence[str], None] = '8c6f2f87a123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
