"""Added stock tracking to scrap

Revision ID: 16013b2b2624
Revises: 54ff53b8e92c
Create Date: 2026-08-31 10:57:18.609430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16013b2b2624'
down_revision: Union[str, Sequence[str], None] = '54ff53b8e92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrap_types', sa.Column('stock', sa.Float(), nullable=True))
    op.add_column('scrap_types', sa.Column('min_stock', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrap_types', 'min_stock')
    op.drop_column('scrap_types', 'stock')
    # ### end Alembic commands ###
