"""add quotations

Revision ID: 4b7ab4d8530e
Revises: e992a4c13b06
Create Date: 2026-08-12 12:39:51.807234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7ab4d8530e'
down_revision: Union[str, Sequence[str], None] = 'e992a4c13b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_no', sa.String(length=32), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('po_reference', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('inter_state', sa.Integer(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('discount_total', sa.Float(), nullable=False),
    sa.Column('taxable_total', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('round_off', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', 'converted', name='quotationstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_quotation_date'), 'quotations', ['quotation_date'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_no'), 'quotations', ['quotation_no'], unique=True)
    op.create_table('quotation_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('hsn', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('taxable', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_lines')
    op.drop_index(op.f('ix_quotations_quotation_no'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_date'), table_name='quotations')
    op.drop_table('quotations')
    # ### end Alembic commands ###
