"""add bill of materials

Revision ID: 54ff53b8e92c
Revises: fa1499539847
Create Date: 2026-08-28 14:41:39.866381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ff53b8e92c'
down_revision: Union[str, Sequence[str], None] = 'fa1499539847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_of_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expected_scrap_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_of_materials_product_id'), 'bill_of_materials', ['product_id'], unique=True)
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bill_of_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_lines_bom_id'), 'bom_lines', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_lines_material_id'), 'bom_lines', ['material_id'], unique=False)
    op.drop_index(op.f('ix_dispatches_delivery_id'), table_name='dispatches')
    op.drop_index(op.f('uq_dispatch_delivery'), table_name='dispatches')
    op.create_unique_constraint('uq_dispatch_delivery', 'dispatches', ['delivery_id'])
    op.alter_column('scrap_types', 'code',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.alter_column('scrap_types', 'code',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_constraint('uq_dispatch_delivery', 'dispatches', type_='unique')
    op.create_index(op.f('uq_dispatch_delivery'), 'dispatches', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_dispatches_delivery_id'), 'dispatches', ['delivery_id'], unique=False)
    op.drop_index(op.f('ix_bom_lines_material_id'), table_name='bom_lines')
    op.drop_index(op.f('ix_bom_lines_bom_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_bill_of_materials_product_id'), table_name='bill_of_materials')
    op.drop_table('bill_of_materials')
    # ### end Alembic commands ###
