"""initial migration

Revision ID: 8a45b22cce62
Revises: 
Create Date: 2026-09-23 11:10:03.927906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a45b22cce62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('gst_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=16), nullable=False),
    sa.Column('financial_year', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('emp_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_emp_code'), 'employees', ['emp_code'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('item_kind', sa.Enum('product', 'material', 'scrap', name='itemkind'), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=160), nullable=False),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'ADJUST', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_entry_date'), 'inventory_movements', ['entry_date'], unique=False)
    op.create_index(op.f('ix_inventory_movements_item_id'), 'inventory_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_item_kind'), 'inventory_movements', ['item_kind'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('gst_number', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_kind'), 'parties', ['kind'], unique=False)
    op.create_index(op.f('ix_parties_name'), 'parties', ['name'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plants_code'), 'plants', ['code'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('hsn', sa.String(length=16), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('raw_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_materials_code'), 'raw_materials', ['code'], unique=True)
    op.create_index(op.f('ix_raw_materials_name'), 'raw_materials', ['name'], unique=False)
    op.create_table('scrap_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('selling_rate', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('min_stock', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrap_types_code'), 'scrap_types', ['code'], unique=True)
    op.create_index(op.f('ix_scrap_types_name'), 'scrap_types', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'accountant', 'operator', name='role'), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workcenters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('capacity_per_hour', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workcenters_code'), 'workcenters', ['code'], unique=True)
    op.create_table('bill_of_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expected_scrap_percent', sa.Float(), nullable=False),
    sa.Column('scrap_type_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scrap_type_id'], ['scrap_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_bom_product_version')
    )
    op.create_index(op.f('ix_bill_of_materials_product_id'), 'bill_of_materials', ['product_id'], unique=False)
    op.create_table('customer_pos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_no', sa.String(length=64), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_pos_customer_id'), 'customer_pos', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_pos_po_no'), 'customer_pos', ['po_no'], unique=True)
    op.create_table('employee_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill', name='uq_employee_skill')
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_skill'), 'employee_skills', ['skill'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('po_reference', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('inter_state', sa.Integer(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('discount_total', sa.Float(), nullable=False),
    sa.Column('taxable_total', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('round_off', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('balance_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', 'cancelled', 'partial', name='invoicestatus'), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_signature'), 'invoices', ['signature'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_no', sa.String(length=32), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('po_reference', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('inter_state', sa.Integer(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('discount_total', sa.Float(), nullable=False),
    sa.Column('taxable_total', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('round_off', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', 'converted', name='quotationstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_quotation_date'), 'quotations', ['quotation_date'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_no'), 'quotations', ['quotation_no'], unique=True)
    op.create_table('routings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_routing_product_version')
    )
    op.create_index(op.f('ix_routings_product_id'), 'routings', ['product_id'], unique=False)
    op.create_table('scrap_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=32), nullable=False),
    sa.Column('scrap_type_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['scrap_type_id'], ['scrap_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrap_entries_entry_date'), 'scrap_entries', ['entry_date'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_code', sa.String(length=64), nullable=False),
    sa.Column('purchase_rate', sa.Float(), nullable=False),
    sa.Column('minimum_order_qty', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('plant_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_plant_id'), 'warehouses', ['plant_id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bill_of_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_lines_bom_id'), 'bom_lines', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_lines_material_id'), 'bom_lines', ['material_id'], unique=False)
    op.create_table('customer_po_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_po_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_po_id'], ['customer_pos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('hsn', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('taxable', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('routing_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_order_date'), 'production_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_production_orders_order_no'), 'production_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_production_orders_product_id'), 'production_orders', ['product_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_no', sa.String(length=32), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=160), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'partially_received', 'received', name='purchaseorderstatus'), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('gst_total', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_date'), 'purchase_orders', ['po_date'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=True)
    op.create_table('quotation_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('hsn', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('taxable', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('routing_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('workcenter_id', sa.String(length=36), nullable=False),
    sa.Column('required_skill', sa.String(length=120), nullable=False),
    sa.Column('setup_minutes', sa.Float(), nullable=False),
    sa.Column('run_minutes_per_unit', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workcenter_id'], ['workcenters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'sequence', name='uq_routing_operation_sequence')
    )
    op.create_index(op.f('ix_routing_operations_routing_id'), 'routing_operations', ['routing_id'], unique=False)
    op.create_index(op.f('ix_routing_operations_workcenter_id'), 'routing_operations', ['workcenter_id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('so_no', sa.String(length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'partially_delivered', 'delivered', 'invoiced', 'cancelled', name='salesorderstatus'), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('quote_no', sa.String(length=32), nullable=False),
    sa.Column('taxable_total', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_order_date'), 'sales_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_sales_orders_quote_id'), 'sales_orders', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_so_no'), 'sales_orders', ['so_no'], unique=True)
    op.create_table('delivery_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_no', sa.String(length=32), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=True),
    sa.Column('so_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('vehicle_no', sa.String(length=32), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('lr_number', sa.String(length=64), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_notes_delivery_date'), 'delivery_notes', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_notes_delivery_no'), 'delivery_notes', ['delivery_no'], unique=True)
    op.create_index(op.f('ix_delivery_notes_sales_order_id'), 'delivery_notes', ['sales_order_id'], unique=False)
    op.create_table('grns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grn_no', sa.String(length=32), nullable=False),
    sa.Column('grn_date', sa.Date(), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('po_no', sa.String(length=32), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grns_grn_date'), 'grns', ['grn_date'], unique=False)
    op.create_index(op.f('ix_grns_grn_no'), 'grns', ['grn_no'], unique=True)
    op.create_table('production_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=32), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('machine', sa.String(length=64), nullable=False),
    sa.Column('workcenter_id', sa.String(length=36), nullable=True),
    sa.Column('routing_id', sa.String(length=36), nullable=True),
    sa.Column('operation_id', sa.String(length=36), nullable=True),
    sa.Column('production_order_id', sa.String(length=36), nullable=True),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('operator', sa.String(length=120), nullable=False),
    sa.Column('shift', sa.String(length=4), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('actual_scrap', sa.Float(), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('accepted_qty', sa.Float(), nullable=False),
    sa.Column('rejected_qty', sa.Float(), nullable=False),
    sa.Column('quality_remarks', sa.Text(), nullable=False),
    sa.Column('scrap_type_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['routing_operations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ),
    sa.ForeignKeyConstraint(['scrap_type_id'], ['scrap_types.id'], ),
    sa.ForeignKeyConstraint(['workcenter_id'], ['workcenters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_entries_batch_no'), 'production_entries', ['batch_no'], unique=True)
    op.create_index(op.f('ix_production_entries_employee_id'), 'production_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_production_entries_entry_date'), 'production_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_production_entries_operation_id'), 'production_entries', ['operation_id'], unique=False)
    op.create_index(op.f('ix_production_entries_production_order_id'), 'production_entries', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_production_entries_routing_id'), 'production_entries', ['routing_id'], unique=False)
    op.create_index(op.f('ix_production_entries_workcenter_id'), 'production_entries', ['workcenter_id'], unique=False)
    op.create_table('production_order_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('production_order_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('workcenter_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_employee_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('planned_qty', sa.Float(), nullable=False),
    sa.Column('completed_qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['routing_operations.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workcenter_id'], ['workcenters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id', 'sequence', name='uq_order_operation_sequence')
    )
    op.create_index(op.f('ix_production_order_operations_assigned_employee_id'), 'production_order_operations', ['assigned_employee_id'], unique=False)
    op.create_index(op.f('ix_production_order_operations_operation_id'), 'production_order_operations', ['operation_id'], unique=False)
    op.create_index(op.f('ix_production_order_operations_production_order_id'), 'production_order_operations', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_production_order_operations_workcenter_id'), 'production_order_operations', ['workcenter_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=True),
    sa.Column('material_name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('received_quantity', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('hsn', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('taxable', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('delivered_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workcenter_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workcenter_id', sa.String(length=36), nullable=False),
    sa.Column('item_kind', sa.String(length=8), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['routing_operations.id'], ),
    sa.ForeignKeyConstraint(['workcenter_id'], ['workcenters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workcenter_id', 'item_kind', 'item_id', name='uq_workcenter_item')
    )
    op.create_index(op.f('ix_workcenter_materials_item_id'), 'workcenter_materials', ['item_id'], unique=False)
    op.create_index(op.f('ix_workcenter_materials_operation_id'), 'workcenter_materials', ['operation_id'], unique=False)
    op.create_index(op.f('ix_workcenter_materials_workcenter_id'), 'workcenter_materials', ['workcenter_id'], unique=False)
    op.create_table('delivery_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_no', sa.String(length=32), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('transporter', sa.String(length=160), nullable=False),
    sa.Column('vehicle_no', sa.String(length=32), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('driver_phone', sa.String(length=32), nullable=False),
    sa.Column('lr_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('planned', 'loading', 'in_transit', 'delivered', 'delayed', name='dispatchstatus'), nullable=False),
    sa.Column('delivered_on', sa.Date(), nullable=True),
    sa.Column('pod_ref', sa.String(length=160), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', name='uq_dispatch_delivery')
    )
    op.create_index(op.f('ix_dispatches_dispatch_date'), 'dispatches', ['dispatch_date'], unique=False)
    op.create_index(op.f('ix_dispatches_dispatch_no'), 'dispatches', ['dispatch_no'], unique=True)
    op.create_table('grn_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grn_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('material_name', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_consumption',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('production_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['production_id'], ['production_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_consumption')
    op.drop_table('grn_lines')
    op.drop_index(op.f('ix_dispatches_dispatch_no'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_dispatch_date'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_table('delivery_lines')
    op.drop_index(op.f('ix_workcenter_materials_workcenter_id'), table_name='workcenter_materials')
    op.drop_index(op.f('ix_workcenter_materials_operation_id'), table_name='workcenter_materials')
    op.drop_index(op.f('ix_workcenter_materials_item_id'), table_name='workcenter_materials')
    op.drop_table('workcenter_materials')
    op.drop_table('sales_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_production_order_operations_workcenter_id'), table_name='production_order_operations')
    op.drop_index(op.f('ix_production_order_operations_production_order_id'), table_name='production_order_operations')
    op.drop_index(op.f('ix_production_order_operations_operation_id'), table_name='production_order_operations')
    op.drop_index(op.f('ix_production_order_operations_assigned_employee_id'), table_name='production_order_operations')
    op.drop_table('production_order_operations')
    op.drop_index(op.f('ix_production_entries_workcenter_id'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_routing_id'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_production_order_id'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_operation_id'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_entry_date'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_employee_id'), table_name='production_entries')
    op.drop_index(op.f('ix_production_entries_batch_no'), table_name='production_entries')
    op.drop_table('production_entries')
    op.drop_index(op.f('ix_grns_grn_no'), table_name='grns')
    op.drop_index(op.f('ix_grns_grn_date'), table_name='grns')
    op.drop_table('grns')
    op.drop_index(op.f('ix_delivery_notes_sales_order_id'), table_name='delivery_notes')
    op.drop_index(op.f('ix_delivery_notes_delivery_no'), table_name='delivery_notes')
    op.drop_index(op.f('ix_delivery_notes_delivery_date'), table_name='delivery_notes')
    op.drop_table('delivery_notes')
    op.drop_index(op.f('ix_sales_orders_so_no'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_quote_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_date'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_routing_operations_workcenter_id'), table_name='routing_operations')
    op.drop_index(op.f('ix_routing_operations_routing_id'), table_name='routing_operations')
    op.drop_table('routing_operations')
    op.drop_table('quotation_lines')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_date'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_production_orders_product_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_no'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_date'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_table('invoice_lines')
    op.drop_table('customer_po_lines')
    op.drop_index(op.f('ix_bom_lines_material_id'), table_name='bom_lines')
    op.drop_index(op.f('ix_bom_lines_bom_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_warehouses_plant_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_scrap_entries_entry_date'), table_name='scrap_entries')
    op.drop_table('scrap_entries')
    op.drop_index(op.f('ix_routings_product_id'), table_name='routings')
    op.drop_table('routings')
    op.drop_index(op.f('ix_quotations_quotation_no'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_date'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_invoices_signature'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_employee_skills_skill'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_customer_pos_po_no'), table_name='customer_pos')
    op.drop_index(op.f('ix_customer_pos_customer_id'), table_name='customer_pos')
    op.drop_table('customer_pos')
    op.drop_index(op.f('ix_bill_of_materials_product_id'), table_name='bill_of_materials')
    op.drop_table('bill_of_materials')
    op.drop_index(op.f('ix_workcenters_code'), table_name='workcenters')
    op.drop_table('workcenters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scrap_types_name'), table_name='scrap_types')
    op.drop_index(op.f('ix_scrap_types_code'), table_name='scrap_types')
    op.drop_table('scrap_types')
    op.drop_index(op.f('ix_raw_materials_name'), table_name='raw_materials')
    op.drop_index(op.f('ix_raw_materials_code'), table_name='raw_materials')
    op.drop_table('raw_materials')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_plants_code'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_parties_name'), table_name='parties')
    op.drop_index(op.f('ix_parties_kind'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_inventory_movements_item_kind'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_entry_date'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_employees_emp_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('company_settings')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
