"""Dispatch Table Added

Revision ID: 8c6f2f87a123
Revises: d4a1d1871413
Create Date: 2026-08-18 09:39:04.212869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6f2f87a123'
down_revision: Union[str, Sequence[str], None] = 'd4a1d1871413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_no', sa.String(length=32), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('transporter', sa.String(length=160), nullable=False),
    sa.Column('vehicle_no', sa.String(length=32), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('driver_phone', sa.String(length=32), nullable=False),
    sa.Column('lr_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('planned', 'loading', 'in_transit', 'delivered', 'delayed', name='dispatchstatus'), nullable=False),
    sa.Column('delivered_on', sa.Date(), nullable=True),
    sa.Column('pod_ref', sa.String(length=160), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_delivery_id'), 'dispatches', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_dispatches_dispatch_date'), 'dispatches', ['dispatch_date'], unique=False)
    op.create_index(op.f('ix_dispatches_dispatch_no'), 'dispatches', ['dispatch_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatches_dispatch_no'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_dispatch_date'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_delivery_id'), table_name='dispatches')
    op.drop_table('dispatches')
    # ### end Alembic commands ###
