"""add sales orders

Revision ID: a2576a538bb3
Revises: 4b7ab4d8530e
Create Date: 2026-08-12 15:29:49.928260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2576a538bb3'
down_revision: Union[str, Sequence[str], None] = '4b7ab4d8530e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('so_no', sa.String(length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column(
    'status',
    sa.Enum(
        'open',
        'partially_delivered',
        'delivered',
        'invoiced',
        'cancelled',
        name='salesorderstatus'
    ),
    nullable=False,
    server_default='open',
),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('quote_no', sa.String(length=32), nullable=False),
    sa.Column('taxable_total', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_order_date'), 'sales_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_sales_orders_quote_id'), 'sales_orders', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_so_no'), 'sales_orders', ['so_no'], unique=True)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('hsn', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('gst_rate', sa.Float(), nullable=False),
    sa.Column('taxable', sa.Float(), nullable=False),
    sa.Column('cgst', sa.Float(), nullable=False),
    sa.Column('sgst', sa.Float(), nullable=False),
    sa.Column('igst', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('delivered_quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order_lines')
    op.drop_index(op.f('ix_sales_orders_so_no'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_quote_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_date'), table_name='sales_orders')
    op.drop_table('sales_orders')
    # ### end Alembic commands ###
