"""Delivery Table Added

Revision ID: d4a1d1871413
Revises: a2576a538bb3
Create Date: 2026-08-18 09:31:19.374080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a1d1871413'
down_revision: Union[str, Sequence[str], None] = 'a2576a538bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_no', sa.String(length=32), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=True),
    sa.Column('so_no', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('vehicle_no', sa.String(length=32), nullable=False),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('lr_number', sa.String(length=64), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_notes_delivery_date'), 'delivery_notes', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_delivery_notes_delivery_no'), 'delivery_notes', ['delivery_no'], unique=True)
    op.create_index(op.f('ix_delivery_notes_sales_order_id'), 'delivery_notes', ['sales_order_id'], unique=False)
    op.create_table('delivery_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_lines')
    op.drop_index(op.f('ix_delivery_notes_sales_order_id'), table_name='delivery_notes')
    op.drop_index(op.f('ix_delivery_notes_delivery_no'), table_name='delivery_notes')
    op.drop_index(op.f('ix_delivery_notes_delivery_date'), table_name='delivery_notes')
    op.drop_table('delivery_notes')
    # ### end Alembic commands ###
