"""add invoice payment tracking

Revision ID: e992a4c13b06
Revises: 24f1d8243a82
Create Date: 2026-08-11 15:18:45.121146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e992a4c13b06'
down_revision: Union[str, Sequence[str], None] = '24f1d8243a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('paid_amount', sa.Float(), nullable=False))
    op.add_column('invoices', sa.Column('balance_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'balance_amount')
    op.drop_column('invoices', 'paid_amount')
    # ### end Alembic commands ###
