"""Scrap Type and BOM Changes

Revision ID: fae5cbfb8d46
Revises: 16013b2b2624
Create Date: 2026-08-31 11:40:38.196511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae5cbfb8d46'
down_revision: Union[str, Sequence[str], None] = '16013b2b2624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_of_materials', sa.Column('scrap_type_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'bill_of_materials', 'scrap_types', ['scrap_type_id'], ['id'])
    op.add_column('production_entries', sa.Column('actual_scrap', sa.Float(), nullable=False))
    op.add_column('production_entries', sa.Column('scrap_type_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'production_entries', 'scrap_types', ['scrap_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_entries', type_='foreignkey')
    op.drop_column('production_entries', 'scrap_type_id')
    op.drop_column('production_entries', 'actual_scrap')
    op.drop_constraint(None, 'bill_of_materials', type_='foreignkey')
    op.drop_column('bill_of_materials', 'scrap_type_id')
    # ### end Alembic commands ###
