/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as FocRouteImport } from './routes/foc'
import { Route as HrRouteImport } from './routes/hr'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as JobworkRouteImport } from './routes/jobwork'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PpcRouteImport } from './routes/ppc'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ScrapRouteImport } from './routes/scrap'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as MastersCustomersRouteImport } from './routes/masters.customers'
import { Route as MastersMaterialsRouteImport } from './routes/masters.materials'
import { Route as MastersProductsRouteImport } from './routes/masters.products'
import { Route as MastersScrapTypesRouteImport } from './routes/masters.scrap-types'
import { Route as MastersSuppliersRouteImport } from './routes/masters.suppliers'
import { Route as MastersWarehousesRouteImport } from './routes/masters.warehouses'
import { Route as ProcurementOrdersRouteImport } from './routes/procurement.orders'
import { Route as ProcurementRequisitionsRouteImport } from './routes/procurement.requisitions'
import { Route as SalesDeliveriesRouteImport } from './routes/sales.deliveries'
import { Route as SalesOrdersRouteImport } from './routes/sales.orders'
import { Route as SalesQuotationsRouteImport } from './routes/sales.quotations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FocRoute = FocRouteImport.update({
  id: '/foc',
  path: '/foc',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const JobworkRoute = JobworkRouteImport.update({
  id: '/jobwork',
  path: '/jobwork',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PpcRoute = PpcRouteImport.update({
  id: '/ppc',
  path: '/ppc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapRoute = ScrapRouteImport.update({
  id: '/scrap',
  path: '/scrap',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCustomersRoute = MastersCustomersRouteImport.update({
  id: '/masters/customers',
  path: '/masters/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersMaterialsRoute = MastersMaterialsRouteImport.update({
  id: '/masters/materials',
  path: '/masters/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersProductsRoute = MastersProductsRouteImport.update({
  id: '/masters/products',
  path: '/masters/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersScrapTypesRoute = MastersScrapTypesRouteImport.update({
  id: '/masters/scrap-types',
  path: '/masters/scrap-types',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersSuppliersRoute = MastersSuppliersRouteImport.update({
  id: '/masters/suppliers',
  path: '/masters/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersWarehousesRoute = MastersWarehousesRouteImport.update({
  id: '/masters/warehouses',
  path: '/masters/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementOrdersRoute = ProcurementOrdersRouteImport.update({
  id: '/procurement/orders',
  path: '/procurement/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRequisitionsRoute = ProcurementRequisitionsRouteImport.update({
  id: '/procurement/requisitions',
  path: '/procurement/requisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDeliveriesRoute = SalesDeliveriesRouteImport.update({
  id: '/sales/deliveries',
  path: '/sales/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales/orders',
  path: '/sales/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQuotationsRoute = SalesQuotationsRouteImport.update({
  id: '/sales/quotations',
  path: '/sales/quotations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/design': typeof DesignRoute
  '/dispatch': typeof DispatchRoute
  '/foc': typeof FocRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/jobwork': typeof JobworkRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/ppc': typeof PpcRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/scrap': typeof ScrapRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/materials': typeof MastersMaterialsRoute
  '/masters/products': typeof MastersProductsRoute
  '/masters/scrap-types': typeof MastersScrapTypesRoute
  '/masters/suppliers': typeof MastersSuppliersRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/requisitions': typeof ProcurementRequisitionsRoute
  '/sales/deliveries': typeof SalesDeliveriesRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/quotations': typeof SalesQuotationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/design': typeof DesignRoute
  '/dispatch': typeof DispatchRoute
  '/foc': typeof FocRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/jobwork': typeof JobworkRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/ppc': typeof PpcRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/scrap': typeof ScrapRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/materials': typeof MastersMaterialsRoute
  '/masters/products': typeof MastersProductsRoute
  '/masters/scrap-types': typeof MastersScrapTypesRoute
  '/masters/suppliers': typeof MastersSuppliersRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/requisitions': typeof ProcurementRequisitionsRoute
  '/sales/deliveries': typeof SalesDeliveriesRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/quotations': typeof SalesQuotationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/design': typeof DesignRoute
  '/dispatch': typeof DispatchRoute
  '/foc': typeof FocRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/jobwork': typeof JobworkRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/ppc': typeof PpcRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/scrap': typeof ScrapRoute
  '/settings': typeof SettingsRoute
  '/transfers': typeof TransfersRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/materials': typeof MastersMaterialsRoute
  '/masters/products': typeof MastersProductsRoute
  '/masters/scrap-types': typeof MastersScrapTypesRoute
  '/masters/suppliers': typeof MastersSuppliersRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/procurement/orders': typeof ProcurementOrdersRoute
  '/procurement/requisitions': typeof ProcurementRequisitionsRoute
  '/sales/deliveries': typeof SalesDeliveriesRoute
  '/sales/orders': typeof SalesOrdersRoute
  '/sales/quotations': typeof SalesQuotationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/design'
    | '/dispatch'
    | '/foc'
    | '/hr'
    | '/inventory'
    | '/invoices'
    | '/jobwork'
    | '/login'
    | '/maintenance'
    | '/ppc'
    | '/production'
    | '/quality'
    | '/scrap'
    | '/settings'
    | '/transfers'
    | '/masters/customers'
    | '/masters/materials'
    | '/masters/products'
    | '/masters/scrap-types'
    | '/masters/suppliers'
    | '/masters/warehouses'
    | '/procurement/orders'
    | '/procurement/requisitions'
    | '/sales/deliveries'
    | '/sales/orders'
    | '/sales/quotations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/design'
    | '/dispatch'
    | '/foc'
    | '/hr'
    | '/inventory'
    | '/invoices'
    | '/jobwork'
    | '/login'
    | '/maintenance'
    | '/ppc'
    | '/production'
    | '/quality'
    | '/scrap'
    | '/settings'
    | '/transfers'
    | '/masters/customers'
    | '/masters/materials'
    | '/masters/products'
    | '/masters/scrap-types'
    | '/masters/suppliers'
    | '/masters/warehouses'
    | '/procurement/orders'
    | '/procurement/requisitions'
    | '/sales/deliveries'
    | '/sales/orders'
    | '/sales/quotations'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/design'
    | '/dispatch'
    | '/foc'
    | '/hr'
    | '/inventory'
    | '/invoices'
    | '/jobwork'
    | '/login'
    | '/maintenance'
    | '/ppc'
    | '/production'
    | '/quality'
    | '/scrap'
    | '/settings'
    | '/transfers'
    | '/masters/customers'
    | '/masters/materials'
    | '/masters/products'
    | '/masters/scrap-types'
    | '/masters/suppliers'
    | '/masters/warehouses'
    | '/procurement/orders'
    | '/procurement/requisitions'
    | '/sales/deliveries'
    | '/sales/orders'
    | '/sales/quotations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  DesignRoute: typeof DesignRoute
  DispatchRoute: typeof DispatchRoute
  FocRoute: typeof FocRoute
  HrRoute: typeof HrRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  JobworkRoute: typeof JobworkRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PpcRoute: typeof PpcRoute
  ProductionRoute: typeof ProductionRoute
  QualityRoute: typeof QualityRoute
  ScrapRoute: typeof ScrapRoute
  SettingsRoute: typeof SettingsRoute
  TransfersRoute: typeof TransfersRoute
  MastersCustomersRoute: typeof MastersCustomersRoute
  MastersMaterialsRoute: typeof MastersMaterialsRoute
  MastersProductsRoute: typeof MastersProductsRoute
  MastersScrapTypesRoute: typeof MastersScrapTypesRoute
  MastersSuppliersRoute: typeof MastersSuppliersRoute
  MastersWarehousesRoute: typeof MastersWarehousesRoute
  ProcurementOrdersRoute: typeof ProcurementOrdersRoute
  ProcurementRequisitionsRoute: typeof ProcurementRequisitionsRoute
  SalesDeliveriesRoute: typeof SalesDeliveriesRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
  SalesQuotationsRoute: typeof SalesQuotationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foc': {
      id: '/foc'
      path: '/foc'
      fullPath: '/foc'
      preLoaderRoute: typeof FocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobwork': {
      id: '/jobwork'
      path: '/jobwork'
      fullPath: '/jobwork'
      preLoaderRoute: typeof JobworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppc': {
      id: '/ppc'
      path: '/ppc'
      fullPath: '/ppc'
      preLoaderRoute: typeof PpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrap': {
      id: '/scrap'
      path: '/scrap'
      fullPath: '/scrap'
      preLoaderRoute: typeof ScrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/customers': {
      id: '/masters/customers'
      path: '/masters/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof MastersCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/materials': {
      id: '/masters/materials'
      path: '/masters/materials'
      fullPath: '/masters/materials'
      preLoaderRoute: typeof MastersMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/products': {
      id: '/masters/products'
      path: '/masters/products'
      fullPath: '/masters/products'
      preLoaderRoute: typeof MastersProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/scrap-types': {
      id: '/masters/scrap-types'
      path: '/masters/scrap-types'
      fullPath: '/masters/scrap-types'
      preLoaderRoute: typeof MastersScrapTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/suppliers': {
      id: '/masters/suppliers'
      path: '/masters/suppliers'
      fullPath: '/masters/suppliers'
      preLoaderRoute: typeof MastersSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/warehouses': {
      id: '/masters/warehouses'
      path: '/masters/warehouses'
      fullPath: '/masters/warehouses'
      preLoaderRoute: typeof MastersWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/orders': {
      id: '/procurement/orders'
      path: '/procurement/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof ProcurementOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/requisitions': {
      id: '/procurement/requisitions'
      path: '/procurement/requisitions'
      fullPath: '/procurement/requisitions'
      preLoaderRoute: typeof ProcurementRequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/deliveries': {
      id: '/sales/deliveries'
      path: '/sales/deliveries'
      fullPath: '/sales/deliveries'
      preLoaderRoute: typeof SalesDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/orders': {
      id: '/sales/orders'
      path: '/sales/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/quotations': {
      id: '/sales/quotations'
      path: '/sales/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof SalesQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  DesignRoute: DesignRoute,
  DispatchRoute: DispatchRoute,
  FocRoute: FocRoute,
  HrRoute: HrRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  JobworkRoute: JobworkRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PpcRoute: PpcRoute,
  ProductionRoute: ProductionRoute,
  QualityRoute: QualityRoute,
  ScrapRoute: ScrapRoute,
  SettingsRoute: SettingsRoute,
  TransfersRoute: TransfersRoute,
  MastersCustomersRoute: MastersCustomersRoute,
  MastersMaterialsRoute: MastersMaterialsRoute,
  MastersProductsRoute: MastersProductsRoute,
  MastersScrapTypesRoute: MastersScrapTypesRoute,
  MastersSuppliersRoute: MastersSuppliersRoute,
  MastersWarehousesRoute: MastersWarehousesRoute,
  ProcurementOrdersRoute: ProcurementOrdersRoute,
  ProcurementRequisitionsRoute: ProcurementRequisitionsRoute,
  SalesDeliveriesRoute: SalesDeliveriesRoute,
  SalesOrdersRoute: SalesOrdersRoute,
  SalesQuotationsRoute: SalesQuotationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
